### ISSUE TITLE
Server-side HTML does not contain styles if a route is not lazy

### ISSUE THREAD

**Issue by grothendeick** [Lomray-Software/vite-ssr-boost#3]
Thanks for your work!

If you set the route as: `{ path: '/home', Component: Home }` (without lazy loading), then server-side HTML does not contain styles in DEV mode.

Changes compared to the demo app:

https://github.com/Lomray-Software/vite-template/compare/prod...grothendeick:vite-template:prod

Reproduction:

https://stackblitz.com/~/github.com/grothendeick/vite-template

![html-without-lazy](https://github.com/Lomray-Software/vite-ssr-boost/assets/1206705/7009331f-ce69-4efe-aace-c0ea4fde9153)

**Comment by MatthewPattell** [comment]
@grothendeick Thanks for reporting. Now it's fixed.

**Comment by grothendeick** [comment]
@MatthewPattell, 
thanks for the quick response.

Now it's working, but only if the non-lazy route is specified last in the file:
```typescript
{
  path: RouteManager.path('notLazy'),
  Component: NotLazyPage,
},
{
  path: RouteManager.path('notLazy2'),
  Component: NotLazyPage2,
}
```

It works for `NotLazyPage2`, but not for `NotLazyPage`.

**Comment by MatthewPattell** [comment]
@grothendeick ah, you can check fix this in [v2.0.0-beta.3](https://github.com/Lomray-Software/vite-ssr-boost/releases/tag/v2.0.0-beta.3)

**Comment by MatthewPattell** [comment]
@grothendeick now it's part of [v2.0.0](https://github.com/Lomray-Software/vite-ssr-boost/releases/tag/v2.0.0)

**Comment by grothendeick** [comment]
@MatthewPattell, v2.0.0 gives the error:

```typescript
Error: Transform failed with 1 error:
C:/repositories/vite-template-prod/src/routes/index.ts:38:75: ERROR: Expected "]" but found ":"
    at failureErrorWithLog (c:\repositories\vite-template-prod\node_modules\esbuild\lib\main.js:1650:15)
    at c:\repositories\vite-template-prod\node_modules\esbuild\lib\main.js:848:29
    at responseCallbacks.<computed> (c:\repositories\vite-template-prod\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (c:\repositories\vite-template-prod\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (c:\repositories\vite-template-prod\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter],
  frame: '\n' +
    '\x1B[33mExpected "]" but found ":"\x1B[39m\n' +
    "36 |          lazy: ()=>n(() => import('@pages/redirect'),'@pages/redirect'),\n" +
    '37 |        },\n' +
    "38 |        { path: RouteManager.path('notLazy'), Component: NotLazyPage },pathId: '@pages/not-lazy',\n" +
    '   |                                                                             ^\n' +
    "39 |        { path: RouteManager.path('notLazy2'), Component: NotLazyPage2 },pathId: '@pages/not-lazy',\n" +
    '40 |      ],\n',
  loc: {
    column: 75,
    file: 'C:/repositories/vite-template-prod/src/routes/index.ts',
    length: 1,
    line: 38,
    lineText: "      { path: RouteManager.path('notLazy'), Component: NotLazyPage },pathId: '@pages/not-lazy',",
    namespace: '',
    suggestion: ']'
  },
  plugin: 'vite:esbuild',
  id: 'C:/repositories/vite-template-prod/src/routes/index.ts',
  pluginCode: "import n from '@lomray/vite-ssr-boost/helpers/import-route';import type { TRouteObject } from '@lomray/vite-ssr-boost/interfaces/route-object';\n" +
    "import AppLayout from '@components/layouts/app';\n" +
    "import Home from '@pages/home';\n" +
    "import NotFound from '@pages/not-found';\n" +
    "import NotLazyPage from '@pages/not-lazy';\n" +
    "import NotLazyPage2 from '@pages/not-lazy';\n" +
    "import RouteManager from '@services/route-manager';\n" +
    "import DetailsRoutes from './details';\n" +
    '\n' +
    '/**\n' +
    ' * Application routes\n' +
    ' */\n' +
    'const routes: TRouteObject[] = [\n' +
    '  {\n' +
    '    ErrorBoundary: NotFound,\n' +
    "    Component: AppLayout,pathId: '@components/layouts/app',\n" +
    '    children: [\n' +
    '      {\n' +
    '        index: true,\n' +
    "        Component: Home,pathId: '@pages/home',\n" +
    '      },\n' +
    '      {\n' +
    "        path: RouteManager.path('details'),\n" +
    '        children: DetailsRoutes,\n' +
    '      },\n' +
    '      {\n' +
    "        path: RouteManager.path('errorBoundary'),\n" +
    "        lazy: ()=>n(() => import('@pages/error-boundary'),'@pages/error-boundary'),\n" +
    '      },\n' +
    '      {\n' +
    "        path: RouteManager.path('nestedSuspense'),\n" +
    "        lazy: ()=>n(() => import('@pages/nested-suspense'),'@pages/nested-suspense'),\n" +
    '      },\n' +
    '      {\n' +
    "        path: RouteManager.path('redirect'),\n" +
    "        lazy: ()=>n(() => import('@pages/redirect'),'@pages/redirect'),\n" +
    '      },\n' +
    "      { path: RouteManager.path('notLazy'), Component: NotLazyPage },pathId: '@pages/not-lazy',\n" +
    "      { path: RouteManager.path('notLazy2'), Component: NotLazyPage2 },pathId: '@pages/not-lazy',\n" +
    '    ],\n' +
    '  },\n' +
    '];\n' +
    '\n' +
    'export default routes;\n'
}

Node.js v18.12.1
``` 

It looks like `pathId ` is inserted in the wrong place:
```typescript
    "      { path: RouteManager.path('notLazy'), Component: NotLazyPage },pathId: '@pages/not-lazy',\n" +
    "      { path: RouteManager.path('notLazy2'), Component: NotLazyPage2 },pathId: '@pages/not-lazy',\n"
```

**Comment by MatthewPattell** [comment]
@grothendeick Oh, I didn't consider code formatting. Well, now I've tried to account for as many cases as possible. [v2.0.1](https://github.com/Lomray-Software/vite-ssr-boost/releases/tag/v2.0.1)

**Comment by grothendeick** [comment]
@MatthewPattell, it still not working, even for the `vite-template` repository without any changes:

```
git clone git@github.com:Lomray-Software/vite-template.git
npm ci
npm run develop
``` 

`view-source:http://127.0.0.1:5173/not-lazy`
![image](https://github.com/Lomray-Software/vite-ssr-boost/assets/1206705/9704510a-2410-4091-81a4-2b0370ece16c)

**Comment by MatthewPattell** [comment]
@grothendeick 
This happens only during the first load; it's normal behavior. Vite is still calculating the modules.
